# Generated by Django 4.0.5 on 2022-07-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=70, verbose_name='number')),
                ('message', models.TextField(max_length=200, verbose_name='message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='time')),
            ],
        ),
    ]
