# Generated by Django 4.0.5 on 2022-07-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_number1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number1',
        ),
        migrations.AddField(
            model_name='number',
            name='session',
            field=models.TextField(default='1', max_length=200, verbose_name='sessoin'),
        ),
    ]
