# Generated by Django 4.0.5 on 2022-07-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_number1_number_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='занчение')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=70, verbose_name='number')),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='комментарии')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.number', verbose_name='сессия')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ratingstar', verbose_name='звезда')),
            ],
        ),
    ]
