# Generated by Django 4.0.5 on 2022-07-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_ratingstar_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberview', models.CharField(max_length=70, verbose_name='number')),
                ('messageview', models.TextField(max_length=200, verbose_name='message')),
                ('sessionview', models.TextField(default='1', max_length=200, verbose_name='sessoin')),
                ('dateview', models.DateTimeField(auto_now_add=True, verbose_name='time')),
            ],
        ),
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.SmallIntegerField(default=0, verbose_name='значение'),
        ),
    ]
