# Generated by Django 4.0.5 on 2022-07-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_numberview_alter_ratingstar_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.numberview', verbose_name='дата'),
        ),
    ]
