# Generated by Django 4.0.5 on 2022-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_rating_session_rating_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(1, 'одна звезда'), (2, 'две здезды'), (3, 'три здезды'), (4, 'четыре здезды'), (5, 'пять здезды')], default=1, verbose_name='значение'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('star', 'message')},
        ),
    ]
