# Generated by Django 4.0.5 on 2022-07-19 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_rating_unique_together_rating_star_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='admin_number',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='admin_ratings', to='chat.number', verbose_name='пользователь_админ'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='number',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='chat.number', verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star_1',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='star_1', to='chat.ratingstar', verbose_name='звезда_1'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star_2',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='star_2', to='chat.ratingstar', verbose_name='звезда_2'),
        ),
    ]
